apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: logger
  name: fluentd
  labels:
    app: fluentd
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      namespace: logger
      labels:
        app: fluentd
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd:v1.2.2
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
        #env:
        #- name: ENV_NAME
        #  value: ENV_VALUE
        #volumeMounts:
        #- name: varlog
        #  value: /var/log
        #  readOnly: false

      #volumes:
      #- name: varlog
      #  hostPath:
      #  path: /var/log
