apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":null,"generation":1,"labels":{"app":"k8s-study","env":"test","version":"1"},"name":"k8s-study","namespace":"k8s-study-space","selfLink":"/apis/extensions/v1beta1/namespaces/k8s-study-space/deployments/k8s-study"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":2,"selector":{"matchLabels":{"app":"k8s-study","env":"test","role":"app","version":"1"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"k8s-study","env":"test","role":"app","version":"1"}},"spec":{"containers":[{"image":"iwanomoto/nginx_test","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/version.html?check=livenessProbe","port":80,"scheme":"HTTP"},"initialDelaySeconds":30,"periodSeconds":3,"successThreshold":1,"timeoutSeconds":1},"name":"nginx-test","ports":[{"containerPort":80,"name":"http","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/version.html?check=readinessProbe","port":80,"scheme":"HTTP"},"initialDelaySeconds":10,"periodSeconds":3,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{"cpu":"100m","memory":"256Mi"},"requests":{"cpu":"50m","memory":"128Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{}}
  creationTimestamp: null
  generation: 1
  labels:
    app: k8s-study
    env: test
    version: "1"
  name: k8s-study
  selfLink: /apis/extensions/v1beta1/namespaces/k8s-study-space/deployments/k8s-study
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: k8s-study
      env: test
      role: app
      version: "1"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "update app to v1.0.1"
      creationTimestamp: null
      labels:
        app: k8s-study
        env: test
        role: app
        version: "1"
    spec:
      containers:
      - image: iwanomoto/nginx_test
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /version.html?check=livenessProbe
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        name: nginx-test
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /version.html?check=readinessProbe
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
