apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
    app: "nginx"
    env: "test"
    ver: "1"
  annotations:
    githash: abcdefg
spec:
  volumes:
    - name: "nginx-data"
      hostPath:
        path: "/var/lib/nginx-data"
  containers:
    - name: nginx-test
      image: iwanomoto/nginx_test
      # imagePullPolicy: Always # Always|Nerver|IfNotPresent
      # command: string
      # workingDir: string
      # volumeMounts:
      #   - name: string
      #     mountPath: string
      #     readOnly: boolean
      ports:
        - name: http
          containerPort: 80
#          hostPort: 80
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /version.html?check=livenessProbe
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /version.html?check=readinessProbe
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 3
      # env:
      #   - name: string
      #     value: string
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 256Mi
      volumeMounts:
        - name: "nginx-data"
          mountPath: "/data"
#  dnsPolicy: Default # Default|ClusterFirst
#  restartPolicy: Always # Always|OnFailure
  # nodeSeletor:
  #   name: string
  # imagePullSecrets:
  #   name: string
